name: Plugin Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: discourse/plugin-ci-action@v1
        with:
          plugin-name: discourse-guardian-links
